// packages/frontend/react/src/components/Login.tsx
import {useOauthMonitor} from "../use-oauth-monitor.js";
import {ButtonExpressionLevel, Overlay, type OverlayProps} from "./Overlay.js";
import {AuthProps} from "../types.js";

export const Login = ({children}: AuthProps) => {
    const [omcContext] = useOauthMonitor();

    const {ui} = omcContext;

    let expressionLevel: ButtonExpressionLevel;

    if (ui.showMustLoginOverlay || ui.loginError) {
        expressionLevel = "expressed";
    } else if (ui.lengthyLogin) {
        expressionLevel = "regular";
    } else {
        expressionLevel = "subdued";
    }

    const overlayProps: OverlayProps = {
        mainMsg: ui.loginError ? "Error Checking Credentials" : ui.showMustLoginOverlay ? "Authentication Required" : "Checking Credentials",
        subMsg: ui.loginError ? "Failed to communicate with server" : !ui.showMustLoginOverlay && ui.lengthyLogin ? "this is taking longer than expected" : undefined,
        button: {
            label: "Login",
            onClick: () => omcContext.omcClient?.handleLogin(true),
            newWindow: true,
            expressionLevel: expressionLevel,
        },
        userCanClose: true,
    }

    return (
        <Overlay {...overlayProps}>
            {children}
        </Overlay>
    );
}

// packages/frontend/svelte/src/lib/components/Login.svelte
<script lang="ts">
    import { getContext } from 'svelte';
    import Overlay from './Overlay.svelte';
    import type { OauthMonitorStore } from '../types';
    import type { OauthMonitorClient } from '@dapperduckling/oauth-monitor-client';

    const store = getContext<OauthMonitorStore>('oauth-monitor-store');
    const client = getContext<OauthMonitorClient>('oauth-monitor-client');

    $: ui = $store.ui;

    // Reactive declarations
    $: expressionLevel = (ui.showMustLoginOverlay || ui.loginError) ? "expressed" :
        (ui.lengthyLogin ? "regular" : "subdued");

    // Type casting for the prop
    $: level = expressionLevel as "expressed" | "regular" | "subdued";

    $: mainMsg = ui.loginError ? "Error Checking Credentials" :
        ui.showMustLoginOverlay ? "Authentication Required" : "Checking Credentials";

    $: subMsg = ui.loginError ? "Failed to communicate with server" :
        (!ui.showMustLoginOverlay && ui.lengthyLogin ? "this is taking longer than expected" : undefined);

    const handleLogin = () => client?.handleLogin(true);
</script>

<Overlay
        {mainMsg}
        {subMsg}
        userCanClose={true}
        buttonLabel="Login"
        buttonAction={handleLogin}
        buttonNewWindow={true}
        buttonExpressionLevel={level}
>
    <slot />
</Overlay>
