// packages/frontend/react/src/components/Overlay.tsx
import type {CSSProperties, ReactNode} from "react";
import { useOauthMonitor } from "../use-oauth-monitor.js";
import {OmcDispatchType} from "../types.js";

export type ButtonExpressionLevel = "subdued" | "regular" | "expressed";

export interface OverlayProps {
    children?: ReactNode;
    mainMsg: string;
    subMsg?: string | undefined;
    userCanClose?: boolean;
    button: {
        label: string;
        onClick: () => void;
        newWindow?: boolean;
        expressionLevel?: ButtonExpressionLevel;
    }
}

const CloseIcon = () => (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
        <line x1="18" y1="6" x2="6" y2="18"></line>
        <line x1="6" y1="6" x2="18" y2="18"></line>
    </svg>
);

const OpenInNewIcon = () => (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" style={{ marginLeft: 6, verticalAlign: 'middle' }}>
        <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path>
        <polyline points="15 3 21 3 21 9"></polyline>
        <line x1="10" y1="14" x2="21" y2="3"></line>
    </svg>
);

export const Overlay = (props: OverlayProps) => {

    // Update the expression level if not set
    props.button.expressionLevel ??= "expressed";

    const [omcContext, omcDispatch] = useOauthMonitor();

    const backdropStyle: CSSProperties = {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1300,
    };

    const cardStyle: CSSProperties = {
        position: 'relative',
        backgroundColor: '#051827',
        color: '#ffffff',
        borderRadius: 8,
        padding: '24px',
        minWidth: 265,
        maxWidth: 420,
        boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.5), 0 10px 10px -5px rgba(0, 0, 0, 0.2)',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: 16,
        fontFamily: 'inherit',
    };

    const closeBtnStyle: CSSProperties = {
        position: 'absolute',
        top: 8,
        right: 8,
        background: 'none',
        border: 'none',
        color: '#9e9e9e',
        cursor: 'pointer',
        padding: 6,
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    };

    const buttonVariantStyle: CSSProperties = props.button.expressionLevel === 'subdued'
        ? {
            backgroundColor: 'transparent',
            border: '1px solid #79b4c3',
            color: '#79b4c3',
            opacity: 0.6,
        }
        : props.button.expressionLevel === 'regular'
        ? {
            backgroundColor: '#79b4c3',
            border: 'none',
            color: '#ffffff',
            opacity: 1,
        }
        : {
            backgroundColor: '#0288d1',
            border: 'none',
            color: '#ffffff',
            opacity: 1,
        };

    const buttonStyle: CSSProperties = {
        width: '100%',
        padding: '10px 16px',
        borderRadius: 6,
        fontWeight: 600,
        fontSize: '0.875rem',
        cursor: 'pointer',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        transition: 'background-color 0.2s, opacity 0.2s',
        ...buttonVariantStyle,
    };

    return (
        <div style={backdropStyle} role="presentation">
            <div
                role="dialog"
                aria-modal="true"
                style={cardStyle}
            >
                {props.userCanClose && (
                    <button
                        type="button"
                        aria-label="close"
                        onClick={() => {
                            omcContext.omcClient?.abortAuthCheck();
                            omcDispatch({type: OmcDispatchType.HIDE_DIALOG});
                        }}
                        style={closeBtnStyle}
                    >
                        <CloseIcon />
                    </button>
                )}
                {props.children}
                <div style={{ textAlign: 'center', width: '100%' }}>
                    <h3 style={{ margin: '8px 0 4px 0', fontSize: '1.25rem', fontWeight: 600, color: 'white' }}>
                        {props.mainMsg}
                    </h3>
                    <div
                        style={{
                            fontSize: '0.75rem',
                            color: '#ef9a9a',
                            fontVariantCaps: 'all-small-caps',
                            marginTop: '-3px',
                            marginBottom: '-17px',
                            minHeight: 18,
                            visibility: props.subMsg !== undefined && props.subMsg.trim() !== '' ? 'visible' : 'hidden',
                        }}
                    >
                        {props.subMsg ?? '\u00A0'}
                    </div>
                </div>
                <button
                    type="button"
                    onClick={props.button.onClick}
                    style={buttonStyle}
                >
                    {props.button.label}
                    {props.button.newWindow && <OpenInNewIcon />}
                </button>
            </div>
        </div>
    );
};

// packages/frontend/svelte/src/lib/components/Overlay.svelte
<script lang="ts">
    import { createEventDispatcher, getContext } from 'svelte';
    import type { OauthMonitorClient } from '@dapperduckling/oauth-monitor-client';
    import type { OauthMonitorStore } from '../store';
    import { OmcDispatchType } from '../types';

    export let mainMsg: string;
    export let subMsg: string | undefined = undefined;
    export let userCanClose: boolean = false;

    // Button Props
    export let buttonLabel: string;
    export let buttonAction: () => void;
    export let buttonNewWindow: boolean = false;
    export let buttonExpressionLevel: "subdued" | "regular" | "expressed" = "expressed";

    const dispatch = createEventDispatcher();
    const client = getContext<OauthMonitorClient>('oauth-monitor-client');
    const store = getContext<OauthMonitorStore>('oauth-monitor-store');

    const handleClose = () => {
        client?.abortAuthCheck();
        store.dispatch({ type: OmcDispatchType.HIDE_DIALOG });
        dispatch('close');
    };
</script>

<!-- Backdrop -->
<div class="fixed inset-0 z-[9999] flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
    <!-- Modal Card -->
    <div class="relative w-full min-w-[265px] max-w-sm flex flex-col items-center rounded-lg bg-[#051827] p-6 text-white shadow-xl border border-gray-800">

        {#if userCanClose}
            <button
                    on:click={handleClose}
                    class="absolute right-2 top-2 p-1 text-gray-500 hover:text-white transition-colors rounded-full hover:bg-white/10"
                    aria-label="Close"
            >
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-5 h-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
            </button>
        {/if}

        <!-- Text Content -->
        <div class="text-center space-y-1 mt-6">
            <h2 class="text-lg font-medium leading-6">{mainMsg}</h2>
            <div class="h-4"> <!-- Fixed height to prevent layout jump -->
                {#if subMsg && subMsg.trim() !== ""}
                    <p class="text-xs font-variant-caps text-[#ef9a9a] uppercase tracking-wide">
                        {subMsg}
                    </p>
                {/if}
            </div>
        </div>

        <!-- Content Slot (Logo, etc) -->
        <div class="w-full flex justify-center mb-2">
            <slot />
        </div>

        <!-- Action Button -->
        <button
                on:click={buttonAction}
                class="w-full flex items-center justify-center gap-2 px-4 py-2 rounded text-sm font-bold uppercase transition-all duration-200"
                class:btn-subdued={buttonExpressionLevel === 'subdued'}
                class:btn-regular={buttonExpressionLevel === 'regular'}
                class:btn-expressed={buttonExpressionLevel === 'expressed'}
        >
            {buttonLabel}
            {#if buttonNewWindow}
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-4 h-4">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                </svg>
            {/if}
        </button>
    </div>
</div>

<style>
    .font-variant-caps {
        font-variant-caps: all-small-caps;
    }

    .btn-subdued {
        background-color: transparent;
        border: 1px solid rgba(255, 255, 255, 0.5);
        color: rgba(255, 255, 255, 0.7);
    }
    .btn-subdued:hover {
        border-color: white;
        color: white;
        background-color: rgba(255, 255, 255, 0.05);
    }

    .btn-regular {
        background-color: #4a4a4a;
        color: white;
    }
    .btn-regular:hover {
        background-color: #5a5a5a;
    }

    .btn-expressed {
        background-color: #79b4c3; /* Info light blue */
        color: white;
        font-weight: 700;
    }
    .btn-expressed:hover {
        background-color: #69a4b3;
    }
</style>
